### ISSUE TITLE
kpcrew don't start

### ISSUE THREAD

**Issue by Kurtili** [prokopiu/kpcrew#161]
Hi Kosta,
thank's for your support. Hope I do it well. 

Hard- and Software information:
Windows 10.0 (build 19043/2)
This is a 64-bit version of Windows.
CPU type: 8664
Physical Memory (total for computer): 34267680768
Maximum Virtual Memory (for X-Plane only): 140737488224256
CPU 0: AMD Ryzen 9 3900X 12-Core Processor              Speed (mhz): 3793
Zibo B737-800X_3_52

Bug-Information:
After starting, kpcrew moves to script/quarantine folder. In the xplane.log:

[Log.txt](https://github.com/prokopiu/kpcrew/files/9992719/Log.txt)

Error Information:
FlyWithLua Info: Start loading script file C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/kpcrew23.lua
FWL: ** Starting KPCrew version 2.3-alpha2 **
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Error: The DataRef "laminar/B738/electric/generic_brightness" does not exist.
FlyWithLua Info: Finished loading script file C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/kpcrew23.lua
FlyWithLua Error: The error seems to be inside of script file C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts/kpcrew23.lua
FlyWithLua Info: 2nd Moved Bad Script to C:\Program Files (x86)/Steam/steamapps/common/X-Plane 11/Resources/plugins/FlyWithLua/Scripts (Quarantine)/kpcrew23.lua
FlyWithLua Info: Load exit file.

**Comment by prokopiu** [comment]
Hallo Kurt,
habe nochmal selbst kpcrew23-alpha3.zip in XP11 ausgepackt und bekomme dieses Fehler nicht. Ich erinnere mich das ich das früher mal hatte und das hing mit der eingesetzten Zibo Version zusammen. Ich weiss nicht ob ich die Zibo Version irgendwo ermitteln kann - aber ich entwickle immer gegen die aktuellste Version in XP11 und XP12 - sonst wird es schwierig die ganzen alten Versionen und ihre Änderungen zu berücksichtigen. Probier bitte die neue Version der Zibo aus.

Was brauche ich noch:
 - FlyWithLua Version - am besten die aktuellste und letzte für XP11: aktuell 2.7.35 wurde vorgestern noch einmal upgedated.

**Comment by Kurtili** [comment]
Hallo Kosta, vielen Dank für Deine Info und Hilfe. Werde ich umsetzen und melde mich dann. 
LG Kurt

**Comment by Kurtili** [comment]
Hallo Kosta, habe es geschafft. Es lag tatsächlich an der Zibo Version. Mit der neuen funktioniert alles einwandfrei. Suuuper. Nochmals vielen Dank. Ein tolles Hilfsmittel für mich bei Vatsim.
LG Kurt

**Comment by prokopiu** [comment]
Werde demnächst alpha4 rausgeben und überarbeite die Abarbeitung der Checklisten und Prozeduren von Grund auf. Während des Worldflights habe ich den Ablauf der Prozeduren und Checklisten nochmal überdacht.
