### ISSUE TITLE
No Clist file in the install ZIP

### ISSUE THREAD

**Issue by Rainy20** [prokopiu/kpcrew#68]
Hi,

This is great work on a FS2CREW like system for X-PLANE, loving it.  My issue is there is no clist.txt file in the ZIP so I cant get the checklist to match.

**Comment by prokopiu** [comment]
Hi Rainy,
you do not need clist.txt any more. I replaced it with my own checklists. Make sure that you replace older versions of kpcrew and install the alpha2 release (alpha3 coming soon with more fixes).
Kosta

**Comment by prokopiu** [comment]
@Rainy20 Let me know when you have things that don't work. I still need to write documentation. You have the flows as a PDF to give you an idea.

**Comment by Rainy20** [comment]
I just did my first flight and everything seemed to work okay.   I'll do some more flights and make a note of anything that seems out of place and list them here.
