### ISSUE TITLE
AP Alarm sounds after takeoff.

### ISSUE THREAD

**Issue by Rainy20** [prokopiu/kpcrew#70]
The AP Alarm sounds just after takeoff.  I believe this is because I am moving the control services to keep the aircraft on course and the PM tries to turn on the Autopilot which instantly disengages due to movement.

**Comment by prokopiu** [comment]
Yes, you have to go to the settings in the EFB and disable the autopilot disconnect on Yoke move. I tried to work around it but could not.

**Comment by prokopiu** [comment]
I cannot get the CMD-A switching stable - removing the CMD-A step for the moment
