### ISSUE TITLE
Gear up after positive rate very slow

### ISSUE THREAD

**Issue by Rainy20** [prokopiu/kpcrew#71]
The gear up command after takeoff seems to take a while.  It can be 10 seconds behind a positive rate call.

**Comment by prokopiu** [comment]
Hi, I have made some changes which will be available with alpha3. Should go a bit faster then. The initial phase after takeoff is difficult. I am still optimizing it.

**Comment by Rainy20** [comment]
In FS2CREW the gear up and flap retract commands are done by pressing the master button and not automatically.  Could this be a possibility?
