### ISSUE TITLE
Dome Light not turned off during or before taxi

### ISSUE THREAD

**Issue by Rainy20** [prokopiu/kpcrew#72]
Not sure if this is a bug or not but the PM sets the dome light on when he sets up the cockpit but does not turn it off before the taxi.  If this isn't a bug could it be added as an option?

**Comment by prokopiu** [comment]
Sounds like an oversight. I check it in the procedure! Thanks!

**Comment by prokopiu** [comment]
the setting of the dome light did not work with the zibo. the dataref was readonly - had to rewrite the function.
