### ISSUE TITLE
Glareshield speed not set

### ISSUE THREAD

**Issue by Rainy20** [prokopiu/kpcrew#78]
Hiya,

Just trying out the new Alpha 3 release and noticed that the PM does not set the glareshield speed to the value set in the take off settings window.  All the data is pulled from the FMC okay when pressing the aircraft data button.  The PM sets all other data okay like course and alt but leaves the speed at 100.

**Comment by prokopiu** [comment]
The function to set the speed used a dataref which is not working in the Zibo. Changed it.
